"""initial_schema

Revision ID: 9dd45042d348
Revises: 
Create Date: 2026-06-10 23:29:20.515540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9dd45042d348'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_is_active'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_conversations_job_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_resume_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_auto_reply_logs_conversation_id'), table_name='auto_reply_logs')
    op.drop_table('auto_reply_logs')
    op.drop_table('settings')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_job_keywords_job_id'), table_name='job_keywords')
    op.drop_index(op.f('ix_job_keywords_word'), table_name='job_keywords')
    op.drop_table('job_keywords')
    op.drop_index(op.f('idx_jobs_batch_id'), table_name='jobs')
    op.drop_index(op.f('idx_source_key'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_resume_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('uq_jobs_seq'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('resume_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=True),
    sa.Column('source_key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512), nullable=False),
    sa.Column('url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024), nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('company', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('salary', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('description', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('raw', mysql.JSON(), nullable=False),
    sa.Column('score', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('decision', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('reasons', mysql.JSON(), nullable=False),
    sa.Column('risks', mysql.JSON(), nullable=False),
    sa.Column('initial_message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('batch_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=True),
    sa.Column('seq', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024), server_default=sa.text("''"), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name='jobs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('uq_jobs_seq'), 'jobs', ['seq'], unique=True)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_resume_id'), 'jobs', ['resume_id'], unique=False)
    op.create_index(op.f('idx_source_key'), 'jobs', ['source_key'], unique=False)
    op.create_index(op.f('idx_jobs_batch_id'), 'jobs', ['batch_id'], unique=False)
    op.create_table('job_keywords',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('job_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=True),
    sa.Column('word', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('job_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024), server_default=sa.text("''"), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('job_keywords_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_job_keywords_word'), 'job_keywords', ['word'], unique=False)
    op.create_index(op.f('ix_job_keywords_job_id'), 'job_keywords', ['job_id'], unique=False)
    op.create_table('events',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64), nullable=False),
    sa.Column('payload', mysql.JSON(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('job_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_table('settings',
    sa.Column('key', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('value', mysql.JSON(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auto_reply_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('conversation_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('job_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024), server_default=sa.text("''"), nullable=True),
    sa.Column('contact_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), server_default=sa.text("''"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_auto_reply_logs_conversation_id'), 'auto_reply_logs', ['conversation_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('job_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=True),
    sa.Column('resume_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=True),
    sa.Column('messages', mysql.JSON(), nullable=False),
    sa.Column('action', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=False),
    sa.Column('ai_reply', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('need_human', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('reason', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('job_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024), server_default=sa.text("''"), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('conversations_ibfk_1')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('conversations_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_conversations_resume_id'), 'conversations', ['resume_id'], unique=False)
    op.create_index(op.f('ix_conversations_job_id'), 'conversations', ['job_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('filename', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('raw_text', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('analysis', mysql.JSON(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('file_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024), nullable=True),
    sa.Column('job_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1024), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_resumes_is_active'), 'resumes', ['is_active'], unique=False)
    # ### end Alembic commands ###
